# Generated by Django 3.2 on 2021-04-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_personvote_voter'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Point',
        ),
    ]
