# Generated by Django 3.2 on 2021-04-21 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_delete_personvote'),
        ('voting', '0002_rename_vote_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant', to='people.person')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.point')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
