# Generated by Django 3.2 on 2021-04-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='point',
        ),
    ]
