# Generated by Django 3.2 on 2021-04-19 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name', '-created'], 'verbose_name_plural': 'persons'},
        ),
        migrations.CreateModel(
            name='PersonVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.vote')),
                ('voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_for', to='people.person')),
                ('voter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
