# Generated by Django 3.2 on 2021-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210419_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_pix',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
