# Generated by Django 3.2 on 2021-04-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_personvote_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter', to='people.person'),
        ),
    ]
