# Generated by Django 3.2 on 2021-04-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_personvote_voter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonVote',
        ),
    ]
